<?php

namespace Syclass\FipeBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Syclass\FipeBundle\Entity\FipeTable;
/**
 * FipeTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FipeTableRepository extends EntityRepository {
    const LIMIT = 100;
    /**
     * Get tables order by month.
     * @return \Syclass\FipeBundle\Entity\FipeTable[]
     **/
    public function findLastest(){
        return $this->getEntityManager()
            ->createQuery('SELECT t FROM SyclassFipeBundle:FipeTable t
                ORDER BY t.month DESC
            ')
            ->getResult();
    }
    /**
     * Get tables no updated in last week.
     * @return \Syclass\FipeBundle\Entity\FipeTable[]
     **/
    public function findNoUpdated(){
        $time = new \DateTime();
        $time->sub(new \DateInterval('P7D'));
        return $this->getEntityManager()
            ->createQuery('SELECT t FROM SyclassFipeBundle:FipeTable t
                WHERE t.checked < :time OR t.checked IS NULL
            ')
            ->setMaxResults(self::LIMIT)
            ->setParameter('time', $time)
            ->getResult();
    }

    /**
     * Save a table object.
     **/
    public function saveTable(FipeTable $table, $checkUpdated = true){
        if($checkUpdated){
            $table->setUpdated(new \DateTime());
        }
        $em = $this->getEntityManager();
        $em->persist($table);
        $em->flush();
    }

}
